[[LinksinJSON]]
== Links in JSON

//-------Remove after TC approval-------

Readers should consider the following warning.

WARNING: This document defines a draft OGC Best Practice on a particular technology or approach. This document is not an OGC Standard and may not be referred to as an OGC Standard. This document is not an official position of the OGC.

//----------------------------------------

=== Introduction
Following the https://tools.ietf.org/html/rfc5988[RFC5988] description, a link is a typed connection between two resources that are identified by internationalized Resource Identifiers (IRIs) [https://tools.ietf.org/html/rfc3987[RFC3987]], and is comprised of:

* a context IRI,
* a link relation type (an initial list of types is in Section-6.2.2 of RFC5988. E.g.: describedBy),
* a target IRI, and
* optionally, target attributes.

This abstract definition was adopted and encoded in XML both by Xlink and Atom in a similar way. The question that is discussed in this section is what is the status of links in JSON and what is the recommendation for the OGC.

In the following subsections, we are exploring existing mechanisms for encoding links in JSON. In these subsections we are presenting examples that establish a link from an object describing the Mississippi river (the context) to the wiki page http://en.wikipedia.org/wiki/Mississippi_River (the target) with the purpose of describing it (relation type _describedBy_).

[[JSON-LD_links_subsection]]
=== JSON-LD
We have been explained JSON-LD in detail in a previous section (please see <<Apply_JSONLD_to_JSON_objects_subsection>>) but, in this subsection, we reflect on a JSON-LD that directly allows to work with links in JSON. In JSON-LD, objects have an _id_ that identifies the _context IRI_. To do that, JSON objects include a property called _@id_. As we know, a JSON object has properties, and JSON-LD defines how to use a key-value property in a particular way that allows expressing a link from this object to other objects.

.Relation between a river and its description expressed in JSON
[source,json]
----
{
	"@id": "http://dbpedia.org/resource/Mississippi_River",
	"describedBy": "http://en.wikipedia.org/wiki/Mississippi_River",
	"name": "Mississippi river"
}
----

Adding JSON-LD to a JSON file introduces the possibility to define links as a property name that has a semantics defined by IANA (such as "describedBy") and the value of the property that has an @id type and shall contain a URI. This is done in a special @context property.

.Context complex property added to a JSON file that defines describedBy as a relation type IANA describedBy.
[source,json]
----
{
	"@context": {
		"describedBy": {
			"@id": "http://www.iana.org/assignments/relation/describedby",
			"@type": "@id"
		}
	}
}
----

Both JSON fragments can be combined in a single JSON-LD document

.Direct combination of the JSON example and the JSON-LD context semantic definition.
[source,json]
----
{
	"@context": {
		"name": "http://schema.org/name",
		"describedBy": {
			"@id": "http://www.iana.org/assignments/relation/describedby",
			"@type": "@id"
		}
	},
	"@id": "http://dbpedia.org/resource/Mississippi_River",
	"describedBy": "http://en.wikipedia.org/wiki/Mississippi_River",
	"name": "Mississippi river"
}
----

JSON-LD allows for a more elegant notation that defines abbreviated namespaces that can be reused later.

.A more elegant version of the JSON example and the JSON-LD context semantic definition using namespaces.
[source,json]
----
{
	"@context": {
		"iana_rel": "http://www.iana.org/assignments/relation/",
		"dbpedia": "http://dbpedia.org/resource/",
		"wiki": "http://en.wikipedia.org/wiki/",
		"schema": "http://schema.org/",

		"name": "schema:name",
		"describedBy": {
			"@id": "iana_rel:describedby",
			"@type": "@id"
		}
	},
	"@id": "dbpedia:Mississippi_River",
	"describedBy": "wiki:Mississippi_River",
	"name": "Mississippi river"
}
----

JSON-LD can be automatically converted to RDF triples. In the conversion, done using the JSON-LD playground, the second triple expresses that the _dbpedia_ id (the context IRI) is _describedBy_ (the link relation type) a _wikipedia_ URL (the target IRI).

[source,RDF]
----
<http://dbpedia.org/resource/Mississippi_River> <http://schema.org/name> "Mississippi river" .
<http://dbpedia.org/resource/Mississippi_River> <http://www.iana.org/assignments/relation/describedby> <http://en.wikipedia.org/wiki/Mississippi_River> .
----

In brief: an object expresses a link by adding a property name that is the _relation_ and a value that acts as the target.

=== Hypertext Application Language

Hypertext Application Language (HAL) is a simple format that tries to give a consistent and easy way to express hyperlinks between resources. It was defined by Mike Kelly, that is a software engineer from the UK that runs an http://stateless.co/[API consultancy] helping companies design and build APIs. HAL has been submitted to the IETF for standardization, however it does not appear to have progressed beyond https://tools.ietf.org/html/draft-kelly-json-hal-08[draft stage]. Nonetheless, HAL has been implemented in a number of products for example https://docs.microsoft.com/en-us/iis-administration/api/hal[Microsoft IIS] and https://docs.camunda.org/manual/7.4/reference/rest/overview/hal/[Camunda].

.HAL notation for JSON links
[source,json]
----
{
	"@id": "http://dbpedia.org/resource/Mississippi_River",
	"name": "Mississippi river",
	"_links": {
		"describedBy": { "href": "http://en.wikipedia.org/wiki/Mississippi_River" }
	}
}
----

=== Atom link reencoded in JSON
The book http://shop.oreilly.com/product/9780596801694.do["RESTful Web Services Cookbook; Solutions for Improving Scalability and Simplicity"] By Subbu Allamaraju, in its chapter "How to Use Links in JSON Representations" proposes a direct translation of the Atom xlink notation in two forms:

.Atom translation to JSON. Alternative 1.
[source,json]
----
{
	"@id": "http://dbpedia.org/resource/Mississippi_River",
	"name": "Mississippi river",
	"links": [{
		"rel": "describedBy",
		"href": "http://en.wikipedia.org/wiki/Mississippi_River"
	}]
}
----

This approach is consistent with what is proposed and generalized for applying it in JSON Schema:  http://json-schema.org/latest/json-schema-hypermedia.html[JSON Hyper-Schema: A Vocabulary for Hypermedia Annotation of JSON].

There is also a more compact format alternative.

.Atom translation to JSON. Alternative 2.
[source,json]
----
{
	"@id": "http://dbpedia.org/resource/Mississippi_River",
	"name": "Mississippi river",
	"links": [{
		"describedBy": { "href": "http://en.wikipedia.org/wiki/Mississippi_River" }
	}
	]
}
----

The later alternative has the advantage that checking for a the presence of a "describedBy" linking is easier in JavaScript and, at the same time, looks almost identical to the HAL proposal. It is the alternative chosen by the OWS Context JSON encoding.

.Accessing a link in the alternative 2.
[source,JavaScript]
----
river=JSON.parse("...");
river.links.describedBy[0]
----

To do the same with the first alternative a JavaScript loop checking all links until finding one of the _describedBy_ type will be needed.

If we remove the _grouping_ property "links", then we almost converge to the JSON-LD alternative.

=== Recommendation

It is difficult to formulate a recommendation when so many practices are coexisting. The authors of this guide consider that the JSON-LD alternative has the advantage of simplicity and, at the same time, it is the only alternative ratified and approved by a Standards Development Organization. It has also the advantage to connect with the RDF world. The main disadvantage is that it does not support additional target attributes such as "title", "type" etc.

In the OGC API effort, a direct recoding of xlink in JSON is getting traction and it is the alternative recommended for any OGC API. Links are added by explicitly including a property called _links_, that is an array, each one following this schema:

[source,json]
----
{
  "link": {
    "type": "object",
    "required": [
      "href"
    ],
    "properties": {
      "href": {
        "type": "string",
        "example": "http://data.example.com/buildings/123"
      },
      "rel": {
        "type": "string",
        "example": "alternate"
      },
      "type": {
        "type": "string",
        "pattern": "^(?=[-a-z]{1,127}/[-\\.a-z0-9]{1,127}$)[a-z]+(-[a-z]+)*/[a-z0-9]+([-\\.][a-z0-9]+)*$",
        "example": "application/geo+json"
      },
      "hreflang": {
        "type": "string",
        "example": "en"
      },
      "title": {
        "type": "string",
        "example": "Trierer Strasse 70, 53115 Bonn"
      },
      "length": {
        "type": "integer",
        "minimum": 0
      }
    }
  }
}
----

Sometimes it is so difficult to decided for a single option that groups decide for more than one approach in the same document. This is the case of the SpatioTemporal Asset Catalog (STAC). In the definition of the STAC item two approaches are coexisting (https://github.com/radiantearth/stac-spec/blob/master/item-spec/examples/landsat8-sample.json). On one hand, some links (called _assets_ are mapped in a similar way as the Atom links alternative 2 (_rel_ is the name of the object)

[source,json]
----
{
	"assets" :{
    "thumbnail": {
      "href": "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_thumb_large.jpg",
      "type": "image/jpeg"
    }
  }
}
----

Other links are mapped as Atom links alternative 1 (_rel_ is another property of the link).

[source,json]
----
"links": [
	 { "rel":"self", "href": "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00.json"},
	 { "rel":"alternate", "href": "https://landsatonaws.com/L8/153/025/LC81530252014153LGN00", "type": "text/html"}
]
----
