== From JSON to JSON-LD

=== What is JSON-LD

JSON-LD is a lightweight syntax to encode Linked Data in JSON. Its design allows existing JSON to be interpreted as Linked Data with minimal changes. JSON-LD is 100% compatible with JSON. JSON-LD introduces a universal identifier mechanism for JSON objects via the use of a Uniform Resource Identifier (URI) and a way to associate data types with values.

JSON-LD is considered another Resource Description Framework (RDF) encoding, for use with other Linked Data technologies like SPARQL. Tools are available to transform JSON-LD into other RDF encodings like Turtle (such as the http://json-ld.org/playground/[JSON-LD playground]).

The authors of this document perceive that the current documentation of JSON-LD as confusing and provides many information that is difficult to understand from the point of view of a JSON and XML user. That is why another approach in explaining how to use JSON-LD is presented here.

[[Apply_JSONLD_to_JSON_objects_subsection]]
=== Applying JSON-LD to JSON objects: minimum example
The main objective of JSON-LD is to define object identifiers and data types identifiers, on top of JSON objects. The identifiers used for objects and data types are unique URIs that provide extra semantics because they reuse definitions on the web (semantic web).

First of all, JSON-LD defines two specific properties for each object: @id and @type that can be populated with the identifier of the object and the complex data type identifier for the object. Please note that even if JSON and JavaScript do *not* provide classes, in JSON-LD we assign a class name (a.k.a. data type) to an object. In this example, we start by defining the Mississippi river.

.Minimum example of a river object as a JSON-LD object
[source,json]
----
{
    "@id": "http://dbpedia.org/page/Mississippi_River",
    "@type": "http://dbpedia.org/ontology/River"
}
----

Within the context of RDF, a triple is a construct built from a subject, predicate and an object. The conversion to RDF results in a single triple stating that the Mississippi river is of a river type.

.Conversion to the minimum example of a river object to RDF triples
[source,turtle]
----
<http://dbpedia.org/page/Mississippi_River> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/River> .
----

[NOTE]
====
In this section, all conversions to RDF triples have been derived automatically for the JSON-LD precedent examples using the JSON-LD playground
====


=== JSON-LD encoding for JSON objects properties

To add a property to the Mississippi river we should define the semantics of the property by associating a URI to it. To do this we need to also add a @context property. Here we have two possibilities:

* reuse a preexisting vocabulary
* create our own vocabulary

In this example we are adding a _name_ to a river resulting on a second triple associated to the object id. In this case we reuse the schema.org vocabulary to define the semantics of the word _name_. Note that http://schema.org/ is actually a URL to a JSON-LD @context document that is in the root of the web server defining the actual and complete schema.org vocabulary.

.Adding a name property to a JSON-LD object using a pre-existing vocabulary
[source,json]
----
{
    "@context": "http://schema.org/",
    "@id": "http://dbpedia.org/page/Mississippi_River",
    "@type": "http://dbpedia.org/ontology/River",
    "name": "Mississippi river"
}
----

.Conversion to a named river object encoded as RDF triples
[source,turtle]
----
<http://dbpedia.org/page/Mississippi_River> <http://schema.org/name> "Mississippi river" .
<http://dbpedia.org/page/Mississippi_River> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/River> .
----

As a second alternative, when the appropriate vocabulary in the JSON-LD format is not available, we can define the needed term on-the-fly as embedded content in the @context section of the JSON instance.

.Adding a name property to JSON-LD object defined elsewhere
[source,json]
----
{
    "@context": {
        "name": "http://www.opengis.net/def/ows-common/name"
    },
    "@id": "http://dbpedia.org/page/Mississippi_River",
    "@type": "http://dbpedia.org/ontology/River",
    "name": "Mississippi river"
}
----

It is also possible to combine two vocabularies, one pre-existing and another embedded. This could be particularly useful if, in the future, the OGC Web Services (OWS) Common standard releases a vocabulary for OGC thereby requiring other OGC web services to extend it. Note that, in this case, @context is defined as an array of an external vocabulary and an internal enumeration of property definitions (in the following example an enumeration of one element).

.Two properties defined combining the two alternatives described before
[source,json]
----
{
    "@context": ["http://schema.org/", {
        "bridges": "http://www.opengis.net/def/ows-common/river/bridge"
    }],
    "@id": "http://dbpedia.org/page/Mississippi_River",
    "@type": "http://dbpedia.org/ontology/River",
    "name": "Mississippi river",
    "bridges": ["Eads Bridge", "Chain of Rocks Bridge"]
}
----

.Conversion to a named river object encoded as RDF triples
[source,turtle]
----
<http://dbpedia.org/page/Mississippi_River> <http://schema.org/name> "Mississippi river" .
<http://dbpedia.org/page/Mississippi_River> <http://www.opengis.net/def/ows-common/river/bridge> "Chain of Rocks Bridge" .
<http://dbpedia.org/page/Mississippi_River> <http://www.opengis.net/def/ows-common/river/bridge> "Eads Bridge" .
<http://dbpedia.org/page/Mississippi_River> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/River> .
----

=== Using namespaces in JSON-LD

Now we can refine the example and provide a more elegant encoding introducing the definition of abbreviated namespaces and their equivalent URI namespace.

.Using abbreviated namespaces in JSON-LD
[source,json]
----
{
    "@context": ["http://schema.org/", {
        "owscommon":"http://www.opengis.net/def/ows-common/",
        "page": "http://dbpedia.org/page/",
        "dbpedia": "http://dbpedia.org/ontology/",
        "bridges": "owscommon:river/bridge"
    }],
    "@id": "page:Mississippi_River",
    "@type": "dbpedia:River",
    "name": "Mississippi river",
    "bridges": ["Eads Bridge", "Chain of Rocks Bridge"]
}
----

=== Defining data types for properties in JSON-LD

By default, JSON-LD considers properties as strings. JSON-LD also permits definition of data types not only for objects but also for individual properties. It is common to define numeric data types.

.Adding data types to properties
[source,json]
----
{
    "@context": ["http://schema.org/", {
        "owscommon":"http://www.opengis.net/def/ows-common/",
        "page": "http://dbpedia.org/page/",
        "dbpedia": "http://dbpedia.org/ontology/",
        "bridges": "owscommon:river/bridge",
		"length": {
			"@id": "http://schema.org/distance",
			"@type": "xsd:float"
    	}
    }],
    "@id": "page:Mississippi_River",
    "@type": "dbpedia:River",
    "name": "Mississippi river",
    "bridges": ["Eads Bridge", "Chain of Rocks Bridge"],
    "length": 3734
}
----

.Conversion of the length of a river object to RDF triples
[source,turtle]
----
<http://dbpedia.org/page/Mississippi_River> <http://schema.org/distance> "3734"^^<http://www.w3.org/2001/XMLSchema#float> .
[...]
----

=== Ordered and unordered arrays in JSON-LD

An interesting aspect of JSON-LD is that it overwrites the behavior of JSON arrays. In JSON, arrays of values are sorted _lists_ but in JSON-LD arrays are _sets_ with no order. This way, in the previous examples, _bridges_ is an array but the conversion to RDF is done in a way that "Eads Bridge" and "Chain of Rocks Bridge" are associated with the Mississippi river with no order. In general, this is not a problem because most arrays are only _sets_ of values. Nevertheless, sometimes order is important for example in a list of coordinates representing a line or a polygon border (imagine what could happen if only one coordinate is out or order!!). Fortunately, there is a way to declare that the array values order is important: using "@container": "@list".

.Example where the order of the list of bridges is important
[source,json]
----
{
    "@context": ["http://schema.org/", {
        "owscommon":"http://www.opengis.net/def/ows-common/",
        "page": "http://dbpedia.org/page/",
        "dbpedia": "http://dbpedia.org/ontology/",
        "bridges": {
          	"@id": "owscommon:river/bridge",
            "@container": "@list"
        }
   }],
    "@id": "page:Mississippi_River",
    "@type": "dbpedia:River",
    "name": "Mississippi river",
    "bridges": ["Eads Bridge", "Chain of Rocks Bridge"]
}
----

.Transformation, to RDF triples, of a list of bridges where order is important
[source,json]
----
<http://dbpedia.org/page/Mississippi_River> <http://schema.org/name> "Mississippi river" .
<http://dbpedia.org/page/Mississippi_River> <http://www.opengis.net/def/ows-common/river/bridge> _:b0 .
<http://dbpedia.org/page/Mississippi_River> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/River> .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "Eads Bridge" .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1 .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "Chain of Rocks Bridge" .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
----

Please note that lists of lists are not allowed in JSON-LD making it impossible to transform two-dimensional (2D) arrays of coordinates. This issue is being discussed in <<Geospatial_dimension_in_JSON>>.

A special kind of data type is "@id". This indicates that a property points to another object _id_ that can be in the same document or elsewhere in the linked data web. This is the way that JSON-LD is able to define links between objects as previously discussed in <<JSON-LD_links_subsection>>.

[source,json]
----
{
    "@context": ["http://schema.org/", {
        "owscommon":"http://www.opengis.net/def/ows-common/",
        "page": "http://dbpedia.org/page/",
        "dbpedia": "http://dbpedia.org/ontology/",
        "wiki": "http://en.wikipedia.org/wiki/Mississippi_River",
		"describedBy": {
			"@id": "http://www.iana.org/assignments/relation/describedby",
			"@type": "@id"
		}
    }],
    "@id": "page:Mississippi_River",
    "@type": "dbpedia:River",
    "name": "Mississippi river",
    "describedBy":  "wiki:Mississippi_River"
}
----

.Conversion to a river object related to another object encoded as RDF triples
[source,turtle]
----
<http://dbpedia.org/page/Mississippi_River> <http://schema.org/name> "Mississippi river" .
<http://dbpedia.org/page/Mississippi_River> <http://www.iana.org/assignments/relation/describedby> <http://en.wikipedia.org/wiki/Mississippi_RiverMississippi_River> .
<http://dbpedia.org/page/Mississippi_River> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/River> .
----
